---
- name: Update and upgrade apt packages
  hosts: all
  become: true
  become_method: sudo

  tasks:
    - name: Update packages with apt
      when: ansible_pkg_mgr == 'apt'
      ansible.builtin.apt:
        update_cache: true
      register: apt_update
      until: apt_update is success
      retries: 3
      delay: 10
      become: true

    - name: Upgrade packages with apt
      when: ansible_pkg_mgr == 'apt'
      ansible.builtin.apt:
        upgrade: dist
      register: apt_upgrade
      until: apt_upgrade is success
      retries: 3
      delay: 10
      become: true
