---
- name: Update and upgrade apt packages
  hosts: all 
  tasks:
    - name: Update packages with apt
      become: "{{ 'yes' if 'need_become' in group_names else 'no' }}"
      when: ansible_pkg_mgr == 'apt'
      apt:
        update_cache: yes
        upgrade: no