---
- name: Update and upgrade apt packages
  hosts: all 
  tasks:
    - name: Update packages with apt
      become: "{{ 'yes' if inventory_hostname in groups['need_become'] else 'no' }}"
      when: ansible_pkg_mgr == 'apt'
      apt:
        update_cache: yes
        upgrade: yes